package Vista;

import javax.swing.JOptionPane;
import Modelo.*;
public class frmcliente extends javax.swing.JFrame {

    Controlador.ClienteDAO clienteDao = new Controlador.ClienteDAO();
    Modelo.Cliente Cliente = new Modelo.Cliente();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmcliente.class.getName());

    public frmcliente() {
        initComponents();
       listarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtCorreo = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("Nombres");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 160, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("DNI");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 160, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 255));
        jLabel4.setText("Teléfono");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 160, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 255));
        jLabel5.setText("Correo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 160, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Apellidos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 160, 40));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnRegistrar.setText(" Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, 40));

        btnModificar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 120, 40));

        btnLimpiar.setBackground(new java.awt.Color(255, 102, 102));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(204, 255, 204));
        btnLimpiar.setText(" limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 190, 40));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 120, 40));

        txtCorreo.addActionListener(this::txtCorreoActionPerformed);
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 160, 50));

        txtDni.addActionListener(this::txtDniActionPerformed);
        jPanel1.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 160, 50));

        txtNombres.addActionListener(this::txtNombresActionPerformed);
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 50));

        txtApellidos.addActionListener(this::txtApellidosActionPerformed);
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 160, 50));

        txtTelefono.addActionListener(this::txtTelefonoActionPerformed);
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 160, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 590, 430));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, -1, -1));
        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
if (txtDni.getText().trim().isEmpty() || txtNombres.getText().trim().isEmpty() || txtApellidos.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "DNI, Nombres y Apellidos son campos obligatorios.");
    return;
}

Cliente.setDni(txtDni.getText().trim());
Cliente.setNombres(txtNombres.getText().trim());
Cliente.setApellidos(txtApellidos.getText().trim());
Cliente.setTelefono(txtTelefono.getText().trim());
Cliente.setCorreo(txtCorreo.getText().trim());

if (clienteDao.registrar(Cliente)) {
    JOptionPane.showMessageDialog(this, "Cliente registrado con éxito.");
    limpiarCampos(); 
} else {
    JOptionPane.showMessageDialog(this, "Error al registrar. Compruebe si el DNI ya existe.");
}
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
if (txtDni.getText().trim().isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "El campo DNI es obligatorio para modificar.");
    return;
}

Cliente.setDni(txtDni.getText().trim());
Cliente.setNombres(txtNombres.getText().trim());
Cliente.setApellidos(txtApellidos.getText().trim());
Cliente.setTelefono(txtTelefono.getText().trim());
Cliente.setCorreo(txtCorreo.getText().trim());

if (clienteDao.modificar(Cliente)) {
    javax.swing.JOptionPane.showMessageDialog(this, "Datos del cliente actualizados con éxito.");
  listarClientes();
    txtDni.setText("");
    txtNombres.setText("");
    txtApellidos.setText("");
    txtTelefono.setText("");
    txtCorreo.setText("");
} else {
    javax.swing.JOptionPane.showMessageDialog(this, "No se pudieron actualizar los datos.");
}
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
String dniBuscar = txtDni.getText().trim();
if (dniBuscar.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un DNI para buscar.");
    return;
}

Cliente = clienteDao.buscarPorDni(dniBuscar);

if (Cliente != null) {
    txtNombres.setText(Cliente.getNombres());
    txtApellidos.setText(Cliente.getApellidos());
    txtTelefono.setText(Cliente.getTelefono());
    txtCorreo.setText(Cliente.getCorreo());
} else {
    javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún cliente con ese DNI.");
}
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmcliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
private void limpiarCampos() {
    txtDni.setText("");
    txtNombres.setText("");
    txtApellidos.setText("");
    txtTelefono.setText("");
    txtCorreo.setText("");
}

  private void listarClientes() {
        
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("DNI");
        modelo.addColumn("Nombres");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Teléfono");
        modelo.addColumn("Correo");

        
        Controlador.ClienteDAO clienteDao = new Controlador.ClienteDAO();
        
        // 3. Obtenemos la lista desde el DAO y la recorremos
        // Nota: Tu ClienteDAO debe tener un método llamado 'listar()' o 'listarClientes()' que devuelva un List
        java.util.List<Modelo.Cliente> lista = clienteDao.listar(); 
        
        if (lista != null) {
            for (Modelo.Cliente c : lista) {
                Object[] fila = new Object[5];
                fila[0] = c.getDni();
                fila[1] = c.getNombres();
                fila[2] = c.getApellidos();
                fila[3] = c.getTelefono();
                fila[4] = c.getCorreo();
                modelo.addRow(fila);
            }
        }
        
        tblClientes.setModel(modelo);
    }

   
    }

